from .architecture import WtvViewSet
from .architecture import BImsBootViewSet
from .architecture import BImsPanelViewSet
from .architecture import TmsViewSet
from .architecture import EpgViewSet
from .architecture import SearchViewSet
from .architecture import PicViewSet
from .architecture import PplViewSet
from .architecture import CosEpgViewSet
from .architecture import UicViewSet
from .architecture import MScreenViewSet
from .architecture import DMS2ViewSet
from .architecture import XMppViewSet
from .architecture import NDmsViewSet
from .architecture import TOSViewSet
from .architecture import UCSViewSet
from .architecture import MGSViewSet
from .architecture import NMCViewSet
from .architecture import UBSViewSet
